(cl:defpackage ros_pololu_servo-msg
  (:use )
  (:export
   "<MOTORCALIBRATION>"
   "MOTORCALIBRATION"
   "<MOTORCOMMAND>"
   "MOTORCOMMAND"
   "<MOTORSTATE>"
   "MOTORSTATE"
   "<MOTORSTATELIST>"
   "MOTORSTATELIST"
   "<POLOLU_TRAJECTORYACTION>"
   "POLOLU_TRAJECTORYACTION"
   "<POLOLU_TRAJECTORYACTIONFEEDBACK>"
   "POLOLU_TRAJECTORYACTIONFEEDBACK"
   "<POLOLU_TRAJECTORYACTIONGOAL>"
   "POLOLU_TRAJECTORYACTIONGOAL"
   "<POLOLU_TRAJECTORYACTIONRESULT>"
   "POLOLU_TRAJECTORYACTIONRESULT"
   "<POLOLU_TRAJECTORYFEEDBACK>"
   "POLOLU_TRAJECTORYFEEDBACK"
   "<POLOLU_TRAJECTORYGOAL>"
   "POLOLU_TRAJECTORYGOAL"
   "<POLOLU_TRAJECTORYRESULT>"
   "POLOLU_TRAJECTORYRESULT"
  ))

