// Generated by gencpp from file ros_pololu_servo/MotorRangeRequest.msg
// DO NOT EDIT!


#ifndef ROS_POLOLU_SERVO_MESSAGE_MOTORRANGEREQUEST_H
#define ROS_POLOLU_SERVO_MESSAGE_MOTORRANGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_pololu_servo
{
template <class ContainerAllocator>
struct MotorRangeRequest_
{
  typedef MotorRangeRequest_<ContainerAllocator> Type;

  MotorRangeRequest_()
    : motor_name()  {
    }
  MotorRangeRequest_(const ContainerAllocator& _alloc)
    : motor_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _motor_name_type;
  _motor_name_type motor_name;





  typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotorRangeRequest_

typedef ::ros_pololu_servo::MotorRangeRequest_<std::allocator<void> > MotorRangeRequest;

typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeRequest > MotorRangeRequestPtr;
typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeRequest const> MotorRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_pololu_servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'ros_pololu_servo': ['/home/karan/advanced_robotics_ws/src/ros_pololu/src/ros_pololu_servo/msg', '/home/karan/advanced_robotics_ws/devel/share/ros_pololu_servo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea6f8ac7c07fc33a72a46dab1cefc8d1";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea6f8ac7c07fc33aULL;
  static const uint64_t static_value2 = 0x72a46dab1cefc8d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_pololu_servo/MotorRangeRequest";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string motor_name\n\
";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_pololu_servo::MotorRangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "motor_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.motor_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_POLOLU_SERVO_MESSAGE_MOTORRANGEREQUEST_H
