// Generated by gencpp from file ros_pololu_servo/MotorRangeResponse.msg
// DO NOT EDIT!


#ifndef ROS_POLOLU_SERVO_MESSAGE_MOTORRANGERESPONSE_H
#define ROS_POLOLU_SERVO_MESSAGE_MOTORRANGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_pololu_servo
{
template <class ContainerAllocator>
struct MotorRangeResponse_
{
  typedef MotorRangeResponse_<ContainerAllocator> Type;

  MotorRangeResponse_()
    : min(0.0)
    , max(0.0)
    , direction(0.0)  {
    }
  MotorRangeResponse_(const ContainerAllocator& _alloc)
    : min(0.0)
    , max(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef float _min_type;
  _min_type min;

   typedef float _max_type;
  _max_type max;

   typedef float _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorRangeResponse_

typedef ::ros_pololu_servo::MotorRangeResponse_<std::allocator<void> > MotorRangeResponse;

typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeResponse > MotorRangeResponsePtr;
typedef boost::shared_ptr< ::ros_pololu_servo::MotorRangeResponse const> MotorRangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_pololu_servo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'ros_pololu_servo': ['/home/karan/advanced_robotics_ws/src/ros_pololu/src/ros_pololu_servo/msg', '/home/karan/advanced_robotics_ws/devel/share/ros_pololu_servo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5892eecaa7e34e1c77e0bea237d5e235";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5892eecaa7e34e1cULL;
  static const uint64_t static_value2 = 0x77e0bea237d5e235ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_pololu_servo/MotorRangeResponse";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min\n\
float32 max\n\
float32 direction\n\
";
  }

  static const char* value(const ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorRangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_pololu_servo::MotorRangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_POLOLU_SERVO_MESSAGE_MOTORRANGERESPONSE_H
